# ╭───────────────────────────────────────────────────────────╮
# │ 引入拆分配置                                              │
# ╰───────────────────────────────────────────────────────────╯
include ./conf.d/theme.conf
include ./conf.d/keybinds.conf

# ╭───────────────────────────────────────────────────────────╮
# │ 字体设置                                                  │
# ╰───────────────────────────────────────────────────────────╯
# 主字体（Nerd Font 等宽图标字体）
font_family      OverPassM Nerd Font Mono
# font_family      Maple Mono NF CN
# font_family      FiraCode Nerd Font Mono
# font_family      JetBrainsMono Nerd Font Mono

bold_font        auto
italic_font      auto
bold_italic_font auto

# 字体大小
font_size 12.0

# 中文字符映射（思源类中文字体）
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF,U+20000-U+2A6DF,U+F900-U+FAFF LXGWNeoXiHeiPlus

# Nerd Font 图标区段强制绑定图标字体，避免方块
symbol_map U+E000-U+F8FF  OverPassM Nerd Font Mono
symbol_map U+23FB-U+23FE,U+E0A0-U+E0A3,U+E0B0-U+E0C7,U+E0CA,U+E0CC,U+E0D0-U+E0D4 OverPassM Nerd Font Mono

# 连字开关
# disable_ligatures never

# ╭───────────────────────────────────────────────────────────╮
# │ 光标拖尾效果                                              │
# ╰───────────────────────────────────────────────────────────╯
cursor_trail 100
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# ╭───────────────────────────────────────────────────────────╮
# │ 性能 & 滚动                                               │
# ╰───────────────────────────────────────────────────────────╯
repaint_delay   8
input_delay     2
scrollback_lines 5000

# ╭───────────────────────────────────────────────────────────╮
# │ 窗口基础设置                                              │
# ╰───────────────────────────────────────────────────────────╯
initial_window_width  800
initial_window_height 600

remember_window_size   yes
remember_window_position yes

# 隐藏标题栏，保留窗口边框
hide_window_decorations titlebar-only

# ╭───────────────────────────────────────────────────────────╮
# │ 标签栏样式                                                │
# ╰───────────────────────────────────────────────────────────╯
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled

# ╭───────────────────────────────────────────────────────────╮
# │ 提示音 & 视觉闪烁                                         │
# ╰───────────────────────────────────────────────────────────╯
enable_audio_bell no
visual_bell_duration 0.5
visual_bell_color #4a6f92

# ╭───────────────────────────────────────────────────────────╮
# │ 链接、终端环境、通用交互                                  │
# ╰───────────────────────────────────────────────────────────╯
detect_urls yes
url_color #d7cf8f
url_style straight

shell_integration enabled
term xterm-kitty

# 动态透明度
dynamic_background_opacity yes

# 选中自动复制
copy_on_select yes

# 鼠标映射
mouse_map right press ungrabbed paste_from_selection
mouse_map shift+left press ungrabbed mouse_selection extend

# 布局预设 (栈布局 + 等分分割)
enabled_layouts splits:equalize_on_close=true, stack

