# 不清空默认快捷键
clear_all_shortcuts no

# 全局修饰键
kitty_mod ctrl+shift

# ── 快捷键 ──────────────────────────────────────────────────────────────

# 布局切换: 栈布局
map alt+z toggle_layout stack

# 选择url
map alt+e open_url_with_hints

# 打开指定的网站
# map alt+l open_url https://github.com

# 标签页操作
map alt+t new_tab
map alt+w close_tab

# 标签页左右移动
map ctrl+shift+. move_tab_forward
map ctrl+shift+, move_tab_backward

# 快速跳转指定标签页
map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5

# 窗格分割：垂直 / 水平
map alt+\ launch --location=vsplit
map alt+- launch --location=hsplit

# 前后标签页切换
map alt+[ previous_tab
map alt+] next_tab

# 重新加载配置
map kitty_mod+f5 load_config_file
map kitty_mod+, load_config_file

# 切换窗口透明度
map --allow-fallback=shifted,ascii ctrl+shift+alt+o set_background_opacity 0.5
map --allow-fallback=shifted,ascii ctrl+shift+alt+l set_background_opacity 1.0

# 切换最大化状态
map alt+m toggle_maximized
