$CONFIGS = $HOME/.config/hypr/configs
# $CONFIGS = $XDG_CONFIG_HOME/hypr/configs

source = $CONFIGS/general.conf
source = $CONFIGS/env.conf
source = $CONFIGS/execs.conf
source = $CONFIGS/rules.conf
source = $CONFIGS/keybinds.conf
