# $suspend_cmd = pidof steam || pidof spotify || systemctl suspend

# hypridle 配置文件
general{
    # 当接收到 dbus 锁屏事件时运行的命令（例如：loginctl lock-session）
    lock_cmd = pidof hyprlock || hyprlock      # 避免开启多个 hyprlock 实例
    before_sleep_cmd = loginctl lock-session   # 锁定之前挂起
    after_sleep_cmd = hyprctl dispatch dpms on # 避免按两次键才能显示

    # on_lock_cmd     = notify-send "Session Locked"    # 锁屏时发送通知
    # on_unlock_cmd   = notify-send "Session Unlocked"  # 解锁时发送通知
    # after_sleep_cmd = notify-send "System Resumed"    # 系统唤醒后执行的命令
}

# 超时锁屏
listener {
    timeout = 180 # 3mins
    on-timeout = loginctl lock-session
}

# 超时 DPMS
listener {
    timeout = 300 # 5mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 超时挂起系统
# listener {
#     timeout = 600 # 10mins
#     on-timeout = $suspend_cmd
# }
