$enFont = Iosevka Nerd Font
$cnFont = LXGW Wenkai Mono

# 背景设置
background {
    monitor =
    path =   # 锁屏背景图片路径
    color = rgba(0, 0, 0, 0.9)  # 背景颜色(如果图片不可用)
    blur_size = 8     # 模糊大小
    blur_passes = 3   # 模糊次数
    noise = 0.01      # 轻微噪点效果
    contrast = 1.1    # 提高对比度
    brightness = 0.9  # 降低亮度
}


# 输入框设置
input-field {
    monitor =
    size = 250, 50         # 输入框大小
    outline_thickness = 3  # 边框厚度

    dots_size = 0.33     # 密码点的大小
    dots_spacing = 0.15  # 密码点之间的间距
    dots_center = true   # 密码点居中
    hide_input = false   # 隐藏输入

    outer_color = rgba(255, 255, 255, 0.5)       # 外边框颜色
    inner_color = rgba(0, 0, 0, 0.5)             # 内边框颜色
    font_color = rgba(255, 255, 255, 1.0)        # 字体颜色
    fade_on_empty = true                         # 输入框为空时淡出
    placeholder_text = <i>Enter Password...</i>  # 占位符文本
    rounding = -1                                # 圆角半径
    shadow_passes = 2                            # 阴影效果
    shadow_size = 5                              # 阴影大小
    shadow_color = rgba(0, 0, 0, 0.5)            # 阴影颜色

    position = 0, -50  # 输入框位置
    halign = center    # 水平对齐
    valign = center    # 垂直对齐
}


# 时间显示设置
label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='orange'>$(date +'%H')</span>:<span foreground='green'>$(date +'%M')</span>"
    color = rgba(255, 255, 255, 1.0)  # 字体颜色
    font_size = 72                    # 字体大小
    font_family = Inter Bold          # 使用现代字体

    shadow_passes = 2                  # 阴影效果
    shadow_size = 5                    # 阴影大小
    shadow_color = rgba(0, 0, 0, 0.5)  # 阴影颜色

    position = 0, 100  # 时间显示位置
    halign = center    # 水平对齐
    valign = center    # 垂直对齐
}


# 日期显示设置
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d')"  # 动态显示日期
    # text = cmd[update:1000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/hyprlock_chinese_date.sh  # 动态显示日期
    color = rgba(255, 255, 255, 0.8)  # 字体颜色
    font_size = 24                    # 字体大小
    font_family = Inter Bold         # 使用中等粗细的字体

    shadow_passes = 2                  # 阴影效果
    shadow_size = 4                    # 阴影大小
    shadow_color = rgba(0, 0, 0, 0.5)  # 阴影颜色

    position = 0, 200  # 日期显示位置
    halign = center    # 水平对齐
    valign = center    # 垂直对齐
}
