[default.files]
gitconfig = "~/.gitconfig"
labelmerc = "~/.labelmerc"


# ── 文件类 ────────────────────────────────────────────────────────────
[starship_rainbow.files]
"starship/rainbow.toml" = "~/.config/starship.toml"

[starship_pure.files]
"starship/pure.toml" = "~/.config/starship.toml"


# ── 目录类 ────────────────────────────────────────────────────────────
[wezterm.files]
wezterm = "~/.config/wezterm"

