[default.files]
PowerShell = "~/Documents/PowerShell"
helix = "~/AppData/Roaming/helix"
nushell = "~/AppData/Roaming/nushell"
pip = "~/AppData/Roaming/pip"
wslconfig = "~/.wslconfig"
zed = "~/AppData/Roaming/zed"
