# 输入法
exec-once = fcitx5 --replace -d

# Core
exec-once = hypridle        # 闲置管理守护进程
# exec-once = hyprpm reload   # 插件管理
exec-once = waybar          # top bar
exec-once = swaync          # 通知程序
exec-once = swww-daemon     # 壁纸

# clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --image image --watch cliphist store

# audio
exec-once = easyeffects --gapplication-service

# cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
