# keybind rules
# l ┃ locked          ┃ 锁定状态，即使有输入抑制器（例如锁屏）激活时也能生效
# r ┃ release         ┃ 释放触发，按键释放时触发
# o ┃ longPress       ┃ 长按触发，按键长按时触发
# e ┃ repeat          ┃ 重复触发，按键按住时会重复触发
# n ┃ non-consuming   ┃ 非消耗性，按键/鼠标事件除了触发调度器外，还会传递给当前活动窗口
# m ┃ mouse           ┃ 鼠标相关，按键和鼠标组合成功能
# t ┃ transparent     ┃ 透明性，不能被其他绑定覆盖
# i ┃ ignore mods     ┃ 忽略修饰键，绑定会忽略修饰键
# s ┃ separate        ┃ 分离性，允许在修饰键和按键之间任意组合键，详见: https://wiki.hyprland.org/Configuring/Binds/#keysym-combos
# d ┃ has description ┃ 带有描述，允许为绑定添加描述
# p ┃ passes          ┃ 绕过应用程序的按键绑定抑制请求


$mainMod = Super # Sets "Windows" key as main modifier

$Launcher = wofi --show drun
$Cliphist = pkill wofi || cliphist list | wofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
$FileManager = dolphin
$FileManager = dolphin

bind = Super Shift, Q, exit
bind = Super, Q, killactive
bind = Super, F, exec, hyprctl dispatch togglefloating active; hyprctl dispatch centerwindow
bind = Super, Z, fullscreen, 1
bind = , F11, fullscreen

# apps
bind = Super, T, exec, kitty
bind = Super, Y, exec, ghostty
bind = Super, M, exec, $Launcher
bind = Super, V, exec, $Cliphist
bind = Super, E, exec, $FileManager

# 锁屏
bind = Super Shift, L, exec, hyprlock

# 亮度调整，使用 brightnessctl
bind = Ctrl Shift Alt, X, exec, brightnessctl set 10%+
bind = Ctrl Shift Alt, Z, exec, brightnessctl set 10%-
# dwindle
bind = Super, R, exec, togglesplit
bind = Super, P, exec, pseudo

# Special 工作区
bind = Super, S, togglespecialworkspace, magic
bind = Super Shift, S, movetoworkspace, special:magic

# 窗口之间移动
bind = Super, left,  movefocus, l
bind = Super, right, movefocus, r
bind = Super, up,    movefocus, u
bind = Super, down,  movefocus, d
bind = Super, h, movefocus, l
bind = Super, l, movefocus, r
bind = Super, k, movefocus, u
bind = Super, j, movefocus, d

# 切换工作区
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# 将当前窗口移动到指定工作区
bind = Super Shift, 1, movetoworkspace, 1
bind = Super Shift, 2, movetoworkspace, 2
bind = Super Shift, 3, movetoworkspace, 3
bind = Super Shift, 4, movetoworkspace, 4
bind = Super Shift, 5, movetoworkspace, 5
bind = Super Shift, 6, movetoworkspace, 6
bind = Super Shift, 7, movetoworkspace, 7
bind = Super Shift, 8, movetoworkspace, 8
bind = Super Shift, 9, movetoworkspace, 9
bind = Super Shift, 0, movetoworkspace, 10

# 使用鼠标滚轮浏览工作区
bind = Super, mouse_down, workspace, e+1
bind = Super, mouse_up,   workspace, e-1

# 进入 resize 模式
bind = Super Shift, R, submap, resize
submap = resize
binde = , H, resizeactive, -20 0
binde = , L, resizeactive, 20  0
bind = , Escape, submap, reset
submap = reset

# 使用鼠标左键移动窗口，右键调整窗口大小
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

# 需要 plasterctl
bindl = , XF86AudioNext,  exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay,  exec, playerctl play-pause
bindl = , XF86AudioPrev,  exec, playerctl previous

# 用于调节音量和 LCD 亮度的笔记本电脑多媒体键
bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp,   exec, brightnessctl s 10%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 10%-

# 遍历窗口
bind = Super, Tab, cyclenext,           # 切换焦点到另一个窗口
bind = Super, Tab, bringactivetotop,    # 把窗口带到最顶层, 确保当前聚焦的窗口不会被遮挡(仅适用浮动窗口之间)
